theme:
  name: Azure-ttk-theme-2.1.0
  mode: light
debug-directory: ''
algorithm:
  nb_colors: 4
  thresholds:
    size: 0.1
    monochrome: 25
  minimum-size: 5000
output-directory: W:/home/antoine/img-splitter/images/output
image-path: W:/home/antoine/img-splitter/images/origins/image-3.jpg
